schema_version: 1

context:
  version: 2.0.0

recipe:
  name: human-readable-pkg
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/h/human_readable/human_readable-${{ version }}.tar.gz
  sha256: 56eb9445e560ccfa0695908ae2ec8b0081b86d49eba1a0833bc0ae0f44d6c4e9

build:
  number: 0
  noarch: python

outputs:
  - package:
      name: human_readable
    build:
      noarch: python
      script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
    requirements:
      host:
        - python ${{ python_min }}.*
        - hatchling
        - hatch-vcs
        - pip
      run:
        - python >=${{ python_min }}
    tests:
      - python:
          imports:
            - human_readable
      - requirements:
          run:
            - pip
            - python ${{ python_min }}.*
        script:
          - pip check

  - package:
      name: human-readable
    build:
      noarch: generic
    requirements:
      run:
        - ${{ pin_subpackage("human_readable", exact=True) }}
    tests:
      - python:
          imports:
            - human_readable

about:
  summary: Human Readable
  license: MIT
  license_file: LICENSE
  homepage: https://github.com/staticdev/human-readable

extra:
  feedstock-name: human_readable
  recipe-maintainers:
    - delucchi-cmu
    - staticdev
    - hombit
